import { AlertTriangle, Boxes, ClipboardCheck, Truck } from "lucide-react";
import { Card, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { requireProfile } from "@/lib/auth/session";
import { getDashboardData, getSupplierDashboard } from "@/lib/services/dashboard";
import { formatCurrency, formatNumber } from "@/lib/utils";
import { getXL45Outstanding } from "@/lib/services/xl45";

export default async function DashboardPage() {
  const profile = await requireProfile();
  if (profile.role === "supplier") {
    const data = await getSupplierDashboard(profile);
    return <div className="grid gap-5"><div><h1 className="font-display m-0 text-2xl text-[var(--brand-deep)]">Tổng quan NCC</h1><p className="mt-1 text-sm text-[var(--muted-foreground)]">Phiếu giao, phản hồi và chuyến vận chuyển liên quan đến tài khoản NCC.</p></div><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<ClipboardCheck size={20}/>} label="Phiếu chờ/phản hồi" value={formatNumber(data.pending)}/><Metric icon={<Truck size={20}/>} label="Phiếu giao tháng" value={formatNumber(data.monthDeliveries)}/><Metric icon={<Truck size={20}/>} label="Chuyến tháng" value={formatNumber(data.monthTrips)}/><Metric icon={<Boxes size={20}/>} label="Cước tháng" value={formatCurrency(data.monthCost)}/></section></div>;
  }
  const [data, xl45] = await Promise.all([getDashboardData(profile), getXL45Outstanding()]);
  const warehouse = data.inventory.filter((x) => x.point_kind === "warehouse");
  const isGroupUser = ["foreman","supervisor","worker"].includes(profile.role);
  return <div className="grid gap-5">
    <div><h1 className="font-display m-0 text-2xl text-[var(--brand-deep)]">Tổng quan</h1><p className="mt-1 text-sm text-[var(--muted-foreground)]">{isGroupUser ? `Tình hình của ${profile.group_name || "nhóm"}.` : "Việc cần xử lý, tồn khí và tình hình giao nhận."}</p></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<ClipboardCheck size={20}/>} label="Chờ xử lý" value={formatNumber(data.pendingCount)}/>{!isGroupUser ? <><Metric icon={<AlertTriangle size={20}/>} label="Loại khí tồn thấp" value={formatNumber(data.lowStock.length)} tone="warning"/><Metric icon={<Truck size={20}/>} label="Chuyến tháng này" value={formatNumber(data.monthTrips)}/><Metric icon={<Boxes size={20}/>} label="Cước vận chuyển tháng" value={formatCurrency(data.monthCost)}/></> : null}</section>
    {!isGroupUser && xl45.length ? <Card><div className="flex items-center justify-between gap-3"><CardTitle>XL-45 đang lưu</CardTitle><Badge tone={xl45.some((x:any)=>Number(x.days_held)>15)?"warning":"info"}>{xl45.length} lô đang mở</Badge></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{xl45.map((x:any)=><div key={x.id} className="rounded-lg border border-[var(--border)] bg-[var(--paper)] p-4"><div className="font-bold">{x.product_name}</div><div className="mt-1 text-xs text-[var(--muted-foreground)]">{x.location_name} · giao {String(x.delivered_date).slice(0,10)}</div><div className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><span className="text-xs text-[var(--muted-foreground)]">Đang lưu</span><div className="font-mono-data font-bold">{formatNumber(x.qty_outstanding)}</div></div><div><span className="text-xs text-[var(--muted-foreground)]">Số ngày</span><div className="font-mono-data font-bold">{x.days_held}</div></div><div><span className="text-xs text-[var(--muted-foreground)]">Phí tạm tính</span><div className="font-mono-data font-bold">{formatCurrency(x.accrued_rental)}</div></div></div></div>)}</div></Card> : null}
    {!isGroupUser && data.lowStock.length ? <Card><div className="flex items-center justify-between gap-3"><CardTitle>Cảnh báo tồn thấp</CardTitle><Badge tone="warning">Cần theo dõi</Badge></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.lowStock.map((row)=><div key={`${row.point_code}-${row.product_code}`} className="rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="font-bold">{row.product_name}</div><div className="mt-2 flex items-baseline justify-between"><span className="text-sm text-[var(--muted-foreground)]">Chai đầy</span><strong className="font-mono-data text-xl text-[#92400E]">{formatNumber(row.full_qty)}</strong></div><div className="mt-1 text-xs text-[var(--muted-foreground)]">Ngưỡng: {formatNumber(row.low_threshold)} {row.unit}</div></div>)}</div></Card> : null}
    <Card><CardTitle>{isGroupUser ? `Số chai ${profile.group_name || "nhóm"} đang quản lý` : "Tồn Kho Hậu cần"}</CardTitle><div className="mt-4 overflow-x-auto"><table className="mobile-card-table w-full border-collapse text-sm"><thead><tr className="text-left text-xs text-[var(--muted-foreground)]"><th className="border-b p-3">Loại khí</th><th className="border-b p-3">Đầy</th><th className="border-b p-3">Rỗng</th><th className="border-b p-3">Tổng</th><th className="border-b p-3">Trạng thái</th></tr></thead><tbody>{(isGroupUser ? data.inventory : warehouse).map((row)=>{const low=row.low_threshold!=null&&Number(row.full_qty)<=Number(row.low_threshold);return <tr key={row.product_code}><td data-label="Loại khí" className="border-b p-3 font-bold">{row.product_name}</td><td data-label="Đầy" className="border-b p-3 font-mono-data">{isGroupUser?"—":formatNumber(row.full_qty)}</td><td data-label="Rỗng" className="border-b p-3 font-mono-data">{isGroupUser?"—":formatNumber(row.empty_qty)}</td><td data-label="Tổng" className="border-b p-3 font-mono-data">{formatNumber(row.total_qty)}</td><td data-label="Trạng thái" className="border-b p-3"><Badge tone={isGroupUser?"neutral":low?"warning":"success"}>{isGroupUser?"Đang quản lý":low?"Tồn thấp":"Bình thường"}</Badge></td></tr>})}</tbody></table></div></Card>
  </div>;
}

function Metric({icon,label,value,tone}:{icon:React.ReactNode;label:string;value:string;tone?:"warning"}){return <Card className={tone==="warning"?"border-amber-200":""}><div className="flex items-start justify-between"><div><div className="text-xs font-bold uppercase tracking-wide text-[var(--muted-foreground)]">{label}</div><div className="font-mono-data mt-2 text-2xl font-extrabold">{value}</div></div><div className="rounded-lg bg-[var(--brand)]/10 p-2 text-[var(--brand)]">{icon}</div></div></Card>}
